# Copyright (c) 2024 Ketan Goyal
#
# This software is released under the MIT License.
# https://opensource.org/licenses/MIT

cc_test(
    name = "hexdump_test",
    srcs = [
        "hexdump_test.cpp",
    ],
    data = [
        "hexdump_test.data",
    ],
    deps = [
        "//:hexdump",
        "@gtest//:gtest_main",
    ],
)

cc_test(
    name = "dprint_test",
    srcs = [
        "dprint_test.cpp",
    ],
    deps = [
        "//:dprint",
        "@gtest//:gtest_main",
    ],
)